git:
  quiet: true

language: c

compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y doxygen graphviz

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make clean
  - make UnitTests
  - make GraphRouter
  - make Graph